package cn.yiiguxing.plugin.translate.trans.openai.chat

import com.google.gson.annotations.SerializedName

/**
 * A completion generated by OpenAI.
 *
 * [documentation](https://platform.openai.com/docs/api-reference/chat/create)
 */
data class ChatChoice internal constructor(
    /**
     * Chat choice index.
     */
    @SerializedName("index") val index: Int? = null,

    /**
     * The generated chat message.
     */
    @SerializedName("message") val message: ChatMessage? = null,

    /**
     * The reason why OpenAI stopped generating.
     */
    @SerializedName("finish_reason") val finishReason: String? = null
)
