package cn.yiiguxing.plugin.translate.trans

/**
 * 语言
 */
enum class Lang(val langName: String, val code: String) {
    AUTO("自动检测", "auto"),
    CHINESE("中文", "zh-CN"),
    ENGLISH("英语", "en"),
    CHINESE_TRADITIONAL("中文(繁体)", "zh-TW"),
    ALBANIAN("阿尔巴尼亚语", "sq"),
    ARABIC("阿拉伯语", "ar"),
    AMHARIC("阿姆哈拉语", "am"),
    AZERBAIJANI("阿塞拜疆语", "az"),
    IRISH("爱尔兰语", "ga"),
    ESTONIAN("爱沙尼亚语", "et"),
    BASQUE("巴斯克语", "eu"),
    BELARUSIAN("白俄罗斯语", "be"),
    BULGARIAN("保加利亚语", "bg"),
    ICELANDIC("冰岛语", "is"),
    POLISH("波兰语", "pl"),
    BOSNIAN("波斯尼亚语", "bs"),
    PERSIAN("波斯语", "fa"),
    AFRIKAANS("布尔语(南非荷兰语)", "af"),
    DANISH("丹麦语", "da"),
    GERMAN("德语", "de"),
    RUSSIAN("俄语", "ru"),
    FRENCH("法语", "fr"),
    FILIPINO("菲律宾语", "tl"),
    FINNISH("芬兰语", "fi"),
    FRISIAN("弗里西语", "fy"),
    KHMER("高棉语", "km"),
    GEORGIAN("格鲁吉亚语", "ka"),
    GUJARATI("古吉拉特语", "gu"),
    KAZAKH("哈萨克语", "kk"),
    HAITIAN_CREOLE("海地克里奥尔语", "ht"),
    KOREAN("韩语", "ko"),
    HAUSA("豪萨语", "ha"),
    DUTCH("荷兰语", "nl"),
    KYRGYZ("吉尔吉斯语", "ky"),
    GALICIAN("加利西亚语", "gl"),
    CATALAN("加泰罗尼亚语", "ca"),
    CZECH("捷克语", "cs"),
    KANNADA("卡纳达语", "kn"),
    CORSICAN("科西嘉语", "co"),
    CROATIAN("克罗地亚语", "hr"),
    KURDISH("库尔德语", "ku"),
    LATIN("拉丁语", "la"),
    LATVIAN("拉脱维亚语", "lv"),
    LAO("老挝语", "lo"),
    LITHUANIAN("立陶宛语", "lt"),
    LUXEMBOURGISH("卢森堡语", "lb"),
    ROMANIAN("罗马尼亚语", "ro"),
    MALAGASY("马尔加什语", "mg"),
    MALTESE("马耳他语", "mt"),
    MARATHI("马拉地语", "mr"),
    MALAYALAM("马拉雅拉姆语", "ml"),
    MALAY("马来语", "ms"),
    MACEDONIAN("马其顿语", "mk"),
    MAORI("毛利语", "mi"),
    MONGOLIAN("蒙古语", "mn"),
    BENGALI("孟加拉语", "bn"),
    MYANMAR("缅甸语", "my"),
    HMONG("苗语", "hmn"),
    XHOSA("南非科萨语", "xh"),
    ZULU("南非祖鲁语", "zu"),
    NEPALI("尼泊尔语", "ne"),
    NORWEGIAN("挪威语", "no"),
    PUNJABI("旁遮普语", "pa"),
    PORTUGUESE("葡萄牙语", "pt"),
    PASHTO("普什图语", "ps"),
    CHICHEWA("齐切瓦语", "ny"),
    JAPANESE("日语", "ja"),
    SWEDISH("瑞典语", "sv"),
    SAMOAN("萨摩亚语", "sm"),
    SERBIAN("塞尔维亚语", "sr"),
    SESOTHO("塞索托语", "st"),
    SINHALA("僧伽罗语", "si"),
    ESPERANTO("世界语", "eo"),
    SLOVAK("斯洛伐克语", "sk"),
    SLOVENIAN("斯洛文尼亚语", "sl"),
    SWAHILI("斯瓦希里语", "sw"),
    SCOTS_GAELIC("苏格兰盖尔语", "gd"),
    CEBUANO("宿务语", "ceb"),
    SOMALI("索马里语", "so"),
    TAJIK("塔吉克语", "tg"),
    TELUGU("泰卢固语", "te"),
    TAMIL("泰米尔语", "ta"),
    THAI("泰语", "th"),
    TURKISH("土耳其语", "tr"),
    WELSH("威尔士语", "cy"),
    URDU("乌尔都语", "ur"),
    UKRAINIAN("乌克兰语", "uk"),
    UZBEK("乌兹别克语", "uz"),
    SPANISH("西班牙语", "es"),
    HEBREW("希伯来语", "iw"),
    GREEK("希腊语", "el"),
    HAWAIIAN("夏威夷语", "haw"),
    SINDHI("信德语", "sd"),
    HUNGARIAN("匈牙利语", "hu"),
    SHONA("修纳语", "sn"),
    ARMENIAN("亚美尼亚语", "hy"),
    IGBO("伊博语", "ig"),
    ITALIAN("意大利语", "it"),
    YIDDISH("意第绪语", "yi"),
    HINDI("印地语", "hi"),
    SUNDANESE("印尼巽他语", "su"),
    INDONESIAN("印尼语", "id"),
    JAVANESE("印尼爪哇语", "jw"),
    YORUBA("约鲁巴语", "yo"),
    VIETNAMESE("越南语", "vi");

    companion object {
        fun valueOfCode(code: String): Lang = when (code) {
            "zh-CHS" -> CHINESE
            else -> values().find { it.code.equals(code, ignoreCase = true) }
                    ?: throw IllegalArgumentException("Unknown language " + "code:$code")
        }
    }
}
